### ISSUE TITLE
Ohara Quickstart 0.8.1 Release

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara-quickstart#22]
**ToDo:**
- [x] Create 0.8.1 release doc
~- [ ] Create 0.8 tag~
~- [ ] Change branch and docs versions from 0.8 to 0.8.x~
- [x] Add change log to release wiki page
- [x] Upload ova file and jars to wiki page
- [x] Add tag to release wiki page
- [x] Publish release

**Comment by saivirtue** [comment]
/cc @wu87988622 
Please help me to add new VM files in [release page](https://github.com/oharastream/ohara-quickstart/releases/tag/untagged-8e4b93205b5ac7ce6aa0) :)
