### ISSUE TITLE
Ohara Quickstart 0.9.0 Release

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara-quickstart#31]
**ToDo:**
- [x] Update the docs so it's update to date with 0.9 release (#33)
- [x] Create 0.9.x branch
- [x] Update 0.9.x branch's link (#35)
- [x] Change ohara_version from 0.9.0-SNAPSHOT to 0.9.0 for the release (#40)
- [x] Create release draft
  - [x] Build and attach VM image file to release draft
  - [x] Add 0.9.0 tag
- [x] Publish release

**Comment by konekoya** [comment]
@vitojeng 0.9.0 was just released :)

**Comment by vitojeng** [comment]
Nice! Thanks @konekoya.
