### ISSUE TITLE
Ohara Quickstart 0.10.0 Release

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara-quickstart#48]
- [x] Update docs for ohara 0.10.0 release (#51)
- [x] Create 0.10.x branch
- [x] Change ohara_version from 0.10.0-SNAPSHOT to 0.10.0 for the release (#54)
- [x] Update version from 0.10.0-SNAPSHOT to 0.11.0-SNAPSHOT for the master branch (#53)
- [x] Create release draft
  - [x] Build and attach VM image file to release draft
  - [x] Update the stream jar used in the docs
  - [x] Add 0.10.0 tag
- [x] Publish release
- [x] Change 0.10.0 to 0.10.1-SNAPSHOT for 0.10.x branch (#55)

**Comment by vitojeng** [comment]
不是 release 0.10.0, 是 release 0.10.0-SNAPSHOT
所以上面都可以不必動作

**Comment by jackyoh** [comment]
所以我直接拿 master 的程式碼包一包，丟到 release 的畫面去應該就可以了。
標題： 0.10.0-SNAPSHOT Release

**Comment by vitojeng** [comment]
對, 因為現在就是 0.10.0-SNAPSHOT, 所以就不用改了.
這個 release 的目的是為了測試使用, 一切從簡.

**Comment by jackyoh** [comment]
好，了解。那我把 PR #47 關閉以及 0.10.x 的 branch 刪除
