### ISSUE TITLE
Ohara Quickstart 0.8.0 Release

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara-quickstart#8]
**ToDo:**
- [x] Create 0.8 tag
~~- [ ] Bump snapshot and docs versions~~
- [x] Change branch and docs versions from 0.8 to 0.8.x
~~- [ ] Create ohara product testing report issue~~
- [x] Add change log to release wiki page
~~- [ ] Update 0.8 branch's SNAPSHOT version to 0.8.0~~
~~- [ ] Upload Bintray repo~~
- [x] Add tag to release wiki page
~~- [ ] Add 0.8 binary files to github wiki page (so users can download from there)~~
~~- [ ] Make sure jenkins is able to build and test on both 0.8 and 0.9 branches~~
~~- [ ] Eliminate all 0.8.0-SNAPSHOT images from docker hub~~
- [x] Publish release
